---
apiVersion: v1
kind: Service
metadata:
  name: testwebapp
spec:
  selector:
    app: testwebapp

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: testwebapp}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testwebapp
      track: stable
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: testwebapp
        track: stable
      name: testwebapp
    spec:
      containers:
      - image: mahewitt/testwebapp:latest
        imagePullPolicy: IfNotPresent
        name: testwebapp
        resources:
          limits:
            memory: 0.25G
            cpu: 0.25
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30